{
 "title": "Sui Bridge",
 "tags": [
  "Bridge",
  "Sui"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "SUI_VALIDATOR", "label": "Validator", "query": "${SUI_VALIDATOR}" },
   {
    "name": "instance",
    "label": "Bridge Target",
    "query": {
     "query": "label_values(up{configured=\"true\"},environment)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Build Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Build Version",
   "type": "stat",
   "description": "Shows the current build version of the SUI Bridge Node.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{process=\"bridge\", environment=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SUI Chain ID",
   "type": "stat",
   "description": "Displays the chain identifier of the SUI Chain.",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{process=\"bridge\", environment=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH Chain ID",
   "type": "stat",
   "description": "Displays the chain identifier of the Ethereum Chain.",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{process=\"bridge\", environment=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Enabled",
   "type": "stat",
   "description": "Indicates whether the SUI Bridge client is enabled, showing 'true' or 'false' based on its current status.",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{process=\"bridge\", environment=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Shows the current operational status of the SUI Bridge Node (UP/DOWN).",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"sui_bridge_.*\", job!~\".*_check\", environment=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime Timeline",
   "type": "timeseries",
   "description": "Displays the uptime trend status of the SUI Bridge Node. Green indicates uptime is increasing, and red indicates it is not.",
   "gridPos": { "h": 4, "w": 15, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(uptime{process=\"bridge\", environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Is Bridge Paused",
   "type": "stat",
   "description": "Displays the pause status for both ETH and SUI bridges.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(bridge_eth_bridge_paused{environment=\"$instance\"})",
     "legendFormat": "eth"
    },
    {
     "expr": "max(bridge_sui_bridge_paused{environment=\"$instance\"})",
     "legendFormat": "sui"
    }
   ]
  },
  {
   "title": "Metrics Public Key Status",
   "type": "stat",
   "description": "Checks the health and availability of the SUI Bridge public metrics endpoint (/metrics_pub_key), which exposes the node’s metrics public key used for authenticating pushed metrics.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=~\"sui_bridge_.*_public_key_check\", environment=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metrics Public Key Timeline",
   "type": "timeseries",
   "description": "Tracks the health status of the SUI Bridge public metrics endpoint (/metrics_pub_key) over time, indicating availability and response consistency.",
   "gridPos": { "h": 4, "w": 15, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "probe_success{job=~\"sui_bridge_.*_public_key_check\", environment=~\"$instance\"}",
     "legendFormat": "Public Metrics Key"
    }
   ]
  },
  {
   "title": "Public Endpoint Ingress Status",
   "type": "stat",
   "description": "Shows the current health status of the SUI Bridge public endpoint ingress, indicating whether the endpoint is accessible and responding to requests.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=~\"sui_bridge_.*_ingress_check\", environment=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Public Endpoint Ingress Timeline",
   "type": "timeseries",
   "description": "Tracks the HTTP response status of the SUI Bridge public endpoint over time, indicating HTTP endpoint availability.",
   "gridPos": { "h": 4, "w": 15, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=~\"sui_bridge_.*_ingress_check\", environment=~\"$instance\"}",
     "legendFormat": "Public Endpoint Ingress"
    }
   ]
  },
  {
   "title": "Voting Power",
   "type": "stat",
   "description": "Shows the current voting power distribution within the bridge committee, offering insights into the committee's decision-making influence and individual authority contributions.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(current_bridge_voting_rights{authority=\"$SUI_VALIDATOR\", environment=\"$instance\"}) \n/ \nsum(current_bridge_voting_rights{environment=\"$instance\"}) \n* 100",
     "legendFormat": "Voting Power %"
    }
   ]
  },
  {
   "title": "Last Finalized ETH Block Over Time",
   "type": "timeseries",
   "description": "Displays the latest finalized Ethereum block observed over time.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "bridge_last_finalized_eth_block{environment=\"$instance\"}",
     "legendFormat": "Block Height"
    }
   ]
  },
  {
   "title": "Last Synced ETH Block Over Time",
   "type": "timeseries",
   "description": "Displays the latest synced Ethereum blocks synced for each contract over time.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "bridge_last_synced_eth_blocks{environment=\"$instance\"}",
     "legendFormat": "{{contract_address}}"
    }
   ]
  },
  {
   "title": "Last Sui Checkpoints of Detected Events",
   "type": "timeseries",
   "description": "This only increments when there is a sui event emitted. So it can stay flat when there is not such traffic.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "bridge_last_synced_sui_checkpoints{environment=\"$instance\"}",
     "legendFormat": "{{host}} {{module_name}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Inflight Requests Over Time",
   "type": "timeseries",
   "description": "Displays the number of inflight requests over time, categorized by request type, providing visibility into ongoing operations and potential bottlenecks in request handling.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(bridge_requests_inflight{environment=\"$instance\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Request Received Over Time",
   "type": "timeseries",
   "description": "Displays the rate of received and processed requests over time, categorized by request type, providing visibility into system throughput and processing capacity.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(bridge_requests_received{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Error Requests Rate Over Time",
   "type": "timeseries",
   "description": "Displays the rate of error requests over time, categorized by request type.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(bridge_err_requests{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests P95 Latency",
   "type": "timeseries",
   "description": "Displays the latency distribution for spans in the bridge node service, categorized by span names. Latency is measured in milliseconds and displayed across the 50th, 95th, and 99th percentiles.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(tracing_span_latencies_bucket{environment=\"$instance\"}[$__rate_interval])) by (le, span_name))",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  { "title": "ETH RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "ETH RPC Query Rate Over Time",
   "type": "timeseries",
   "description": "Displays the rate of Ethereum RPC queries processed over time, providing insights into query frequency and system workload trends.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(bridge_eth_rpc_queries{environment=\"$instance\"}[$__rate_interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "ETH RPC P95 Latency",
   "type": "timeseries",
   "description": "Displays the Ethereum RPC query latency for 95th percentile.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(bridge_eth_rpc_queries_latency_bucket{environment=\"$instance\"}[$__rate_interval])) by (le, type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "SUI RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Error Requests Rate Over Time",
   "type": "timeseries",
   "description": "Displays the rate of error requests from Sui RPC over time, categorized by request type.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(bridge_sui_rpc_errors{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Request Signer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Cache Performance Ratio",
   "type": "gauge",
   "description": "Shows the overall performance ratio of the signer cache, indicating the percentage of cache hits vs total cache operations. Higher values indicate better cache efficiency.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_signer_with_cache_hit{environment=\"$instance\"} / (bridge_signer_with_cache_hit{environment=\"$instance\"} + bridge_signer_with_cache_miss{environment=\"$instance\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate by Type Over Time",
   "type": "timeseries",
   "description": "Shows the rate of cache hits per second for different cache types. This metric helps identify which cache types are performing well.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(bridge_signer_with_cache_hit{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache Miss Rate by Type Over Time",
   "type": "timeseries",
   "description": "Shows the rate of cache misses per second for different cache types. Higher values indicate cache inefficiency and may require attention.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(bridge_signer_with_cache_miss{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Balances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Client Gas Coin Balance",
   "type": "stat",
   "description": "Displays the current balance of the gas coin for the SUI Bridge node. The balance is shown in SUI units, with regular updates reflecting the latest state.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bridge_gas_coin_balance{environment=\"$instance\"}) / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDT Vault Balance",
   "type": "stat",
   "description": "Displays the current balance of the USDT vault for the SUI Bridge node. The balance is shown in USDT units, with regular updates reflecting the latest state.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bridge_usdt_vault_balance{environment=\"$instance\"}) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH Vault Balance",
   "type": "stat",
   "description": "Displays the current balance of the Ethereum vault for the SUI Bridge node. The balance is shown in ETH units, with regular updates reflecting the latest state.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bridge_eth_vault_balance{environment=\"$instance\"}) / 100000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LBTC Vault Balance",
   "type": "stat",
   "description": "Displays the current balance of the LBTC vault for the SUI Bridge node. The balance is shown in LBTC units, with regular updates reflecting the latest state.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bridge_lbtc_vault_balance{environment=\"$instance\"}) / 100000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Gas Coin Balance Over Time",
   "type": "timeseries",
   "description": "Shows the timeline of the SUI Gas Balance for the SUI Bridge Node.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(bridge_gas_coin_balance{environment=\"$instance\"}) / 1000000000",
     "legendFormat": "Balance"
    }
   ]
  },
  {
   "title": "USDT Vault Balance Over Time",
   "type": "timeseries",
   "description": "Shows the timeline of the SUI Gas Balance for the SUI Bridge Node.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(bridge_usdt_vault_balance{environment=\"$instance\"}) / 1000000",
     "legendFormat": "Balance"
    }
   ]
  },
  {
   "title": "ETH Vault Balance Over Time",
   "type": "timeseries",
   "description": "Shows the timeline of the SUI Gas Balance for the SUI Bridge Node.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(bridge_eth_vault_balance{environment=\"$instance\"}) / 100000000",
     "legendFormat": "Balance"
    }
   ]
  },
  {
   "title": "LBTC Vault Balance Over Time",
   "type": "timeseries",
   "description": "Shows the timeline of the LBTC Balance for the SUI Bridge Node.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(bridge_lbtc_vault_balance{environment=\"$instance\"}) / 100000000",
     "legendFormat": "Balance"
    }
   ]
  },
  {
   "title": "WBTC Vault Balance",
   "type": "stat",
   "description": "Displays the current balance of the WBTC vault for the SUI Bridge node. The balance is shown in WBTC units, with regular updates reflecting the latest state.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 81 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(bridge_wbtc_vault_balance{environment=\"$instance\"}) / 100000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WBTC Vault Balance Over Time",
   "type": "timeseries",
   "description": "Shows the timeline of the WBTC Balance for the SUI Bridge Node.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(bridge_wbtc_vault_balance{environment=\"$instance\"}) / 100000000",
     "legendFormat": "Balance"
    }
   ]
  },
  { "title": "Watcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Events Rate Over Time",
   "type": "timeseries",
   "description": "Displays the rate of received events in the Sui Watcher over time, providing insights into event processing throughput and anomaly detection.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(bridge_eth_watcher_received_events{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "ETH"
    },
    {
     "expr": "rate(bridge_sui_watcher_received_events{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "SUI"
    }
   ]
  },
  {
   "title": "Unrecognized Events Rate Over Time",
   "type": "timeseries",
   "description": "Displays the rate of unrecognized events in the Sui Watcher over time, providing insights into event processing throughput and anomaly detection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(bridge_sui_watcher_unrecognized_events{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "SUI"
    },
    {
     "expr": "rate(bridge_eth_watcher_unrecognized_events{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "ETH"
    }
   ]
  },
  {
   "title": "Transfers Received Over Time",
   "type": "timeseries",
   "description": "Displays the rate of transfer actions received by the bridge watcher over time, showing both SUI to ETH and ETH to SUI transfer directions.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 91 },
   "targets": [
    {
     "expr": "rate(bridge_sui_watcher_received_actions{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "SUI -> ETH"
    },
    {
     "expr": "rate(bridge_eth_watcher_received_actions{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "ETH -> SUI"
    }
   ]
  },
  {
   "title": "Transfers Approved Over Time",
   "type": "timeseries",
   "description": "Shows the rate of token transfers that have been approved by the bridge committee over time, tracking both ETH to SUI and SUI to ETH transfer approvals.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "rate(bridge_eth_sui_token_transfer_approved{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "ETH -> SUI"
    },
    {
     "expr": "rate(bridge_sui_eth_token_transfer_approved{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "SUI -> ETH"
    }
   ]
  },
  {
   "title": "Transfers Claimed Over Time",
   "type": "timeseries",
   "description": "Tracks the rate of token transfers that have been successfully claimed by users over time, showing completion rates for both ETH to SUI and SUI to ETH transfers.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 99 },
   "targets": [
    {
     "expr": "rate(bridge_eth_sui_token_transfer_claimed{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "ETH -> SUI"
    },
    {
     "expr": "rate(bridge_sui_eth_token_transfer_claimed{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "SUI -> ETH"
    }
   ]
  },
  { "title": "Action Executor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "Action Executor Signing Queue Over Time",
   "type": "timeseries",
   "description": "Shows key metrics for the Bridge Action Executor queue, including totals for received, skipped, and already processed actions, helping monitor queue performance and efficiency.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(bridge_action_executor_signing_queue_received_actions{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "received {{host}} "
    },
    {
     "expr": "rate(bridge_action_executor_already_processed_actions{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "already processed {{host}} "
    },
    {
     "expr": "rate(bridge_action_executor_signing_queue_skipped_actions{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "skipped {{host}} "
    }
   ]
  },
  {
   "title": "Action Executor Execution Queue Over Time",
   "type": "timeseries",
   "description": "Displays metrics for the execution queue in the Bridge Action Executor, including totals for received actions and actions skipped due to pausing, providing insights into queue activity and processing behavior.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(bridge_action_executor_execution_queue_received_actions{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "received {{host}} "
    },
    {
     "expr": "rate(bridge_action_executor_execution_queue_skipped_actions_due_to_pausing{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "skipped processed {{host}} "
    }
   ]
  },
  {
   "title": "Action Executor Errors Over Time",
   "type": "timeseries",
   "description": "Displays error metrics for the Bridge Action Executor, including failures during Sui transaction execution, submission errors, and continuous submission failures, helping identify and address recurring issues.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(bridge_err_build_sui_transaction{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "build sui tx {{host}} "
    },
    {
     "expr": "rate(bridge_err_signature_aggregation{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "sig aggregation {{host}} "
    },
    {
     "expr": "rate(bridge_err_sui_transaction_submission{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "submit sui tx {{host}} "
    },
    {
     "expr": "rate(bridge_err_sui_transaction_submission_too_many_failures{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "submit sui tx too many failure {{host}} "
    },
    {
     "expr": "rate(bridge_err_sui_transaction_execution{environment=\"$instance\"}[$__rate_interval])",
     "legendFormat": "execute sui tx {{host}} "
    }
   ]
  },
  { "title": "Governance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Governance Actions Over Time",
   "type": "timeseries",
   "description": "Monitors governance actions observed by the bridge node over time, tracking important administrative changes and committee decisions that affect bridge operations.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "bridge_observed_governance_actions{environment=\"$instance\", action_type!=\"committee_member_registered\", action_type!=\"committee_member_url_updated\", action_type!=\"new_token_registered\"} > 0 unless bridge_observed_governance_actions{network=\"$network\", job=\"sui-bridge\", action_type!=\"committee_member_registered\", action_type!=\"committee_member_url_updated\", action_type!=\"new_token_registered\"} offset 5m > 0\nor\nbridge_observed_governance_actions{environment=\"$instance\", action_type!=\"committee_member_registered\", action_type!=\"committee_member_url_updated\", action_type!=\"new_token_registered\"} > bridge_observed_governance_actions{network=\"$network\", job=\"sui-bridge\", action_type!=\"committee_member_registered\", action_type!=\"committee_member_url_updated\", action_type!=\"new_token_registered\"} offset 5m\n",
     "legendFormat": "{{action_type}}"
    }
   ]
  }
 ]
}